version: '3.1'
services:
  stats-server:
    build: ./stat/stat-server
    image: service
    container_name: stat-service-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USER=mariac
      - SPRING_DATASOURCE_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: stat-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=mariac

  ewm-service:
    build: ./main-service
    image: main-service
    container_name: main-service-container
    ports:
      - "8080:8080"


      # ewm-db:
  #  image: postgres:14-alpine
